services:
  singlefile-webservice:
    build: .
    container_name: singlefile-webservice-dev
    ports:
      - "8080:8080"
    volumes:
      - ./output:/usr/src/app/output
    restart: unless-stopped
    environment:
      - PORT=8080
      - TIMEOUT=60
      - OUTPUT_DIR=/usr/src/app/output
